/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JPanel;

/**
 *
 * @author paola
 */
public final class AllQueues extends javax.swing.JPanel {
    
    private final JPanel[] panels;
    /**
     * Creates new form AllQueues
     */
    public AllQueues() {
        initComponents();
        panels = new JPanel [4];
        initializePanels();
        
    }

    public void initializePanels(){
        this.panels[0] = this.Level1;
        this.panels[1] = this.Level2;
        this.panels[2] = this.Level3;
        this.panels[3] = this.LevelR;
    }
    
    public void initializeQueue(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LevelR = new javax.swing.JPanel();
        Level3 = new javax.swing.JPanel();
        Level2 = new javax.swing.JPanel();
        Level1 = new javax.swing.JPanel();

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout LevelRLayout = new javax.swing.GroupLayout(LevelR);
        LevelR.setLayout(LevelRLayout);
        LevelRLayout.setHorizontalGroup(
            LevelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        LevelRLayout.setVerticalGroup(
            LevelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(LevelR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        javax.swing.GroupLayout Level3Layout = new javax.swing.GroupLayout(Level3);
        Level3.setLayout(Level3Layout);
        Level3Layout.setHorizontalGroup(
            Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        Level3Layout.setVerticalGroup(
            Level3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(Level3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        javax.swing.GroupLayout Level2Layout = new javax.swing.GroupLayout(Level2);
        Level2.setLayout(Level2Layout);
        Level2Layout.setHorizontalGroup(
            Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        Level2Layout.setVerticalGroup(
            Level2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        javax.swing.GroupLayout Level1Layout = new javax.swing.GroupLayout(Level1);
        Level1.setLayout(Level1Layout);
        Level1Layout.setHorizontalGroup(
            Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        Level1Layout.setVerticalGroup(
            Level1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Level1;
    private javax.swing.JPanel Level2;
    private javax.swing.JPanel Level3;
    private javax.swing.JPanel LevelR;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
