/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.BorderLayout;
import javax.swing.JPanel;


/**
 *
 * @author paola
 */
public class Form extends javax.swing.JFrame {

    private final AllQueues queuesLG;
    private final AllQueues queuesBG;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.queuesLG = new AllQueues();
        this.queuesBG = new AllQueues();
        createQueues(queuesPanelLG, queuesLG);
        createQueues(queuesPanelBG, queuesBG);
        
    }
    
    public void createQueues(JPanel panel, AllQueues pq){
        pq.setSize(230, 200);
        pq.setLocation(0, 0);
        panel.removeAll();
        panel.add(pq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LGPoints = new javax.swing.JLabel();
        BGPoints = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        BGInfo = new javax.swing.JTextArea();
        IAState = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LGInfo = new javax.swing.JTextArea();
        queuesPanelBG = new javax.swing.JPanel();
        queuesPanelLG = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(899, 504));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LGPoints.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LGPoints.setText("0");
        jPanel1.add(LGPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 70, -1));

        BGPoints.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BGPoints.setText("0");
        jPanel1.add(BGPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bugatti");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lamborghini");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jSlider1.setMaximum(20);
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        BGInfo.setColumns(20);
        BGInfo.setRows(5);
        jScrollPane1.setViewportView(BGInfo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 170, 190));

        IAState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IAState.setText("Working");
        jPanel1.add(IAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("The IA is ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel4.setText("0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 30, -1));

        jLabel6.setText("20");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 20, -1));

        LGInfo.setColumns(20);
        LGInfo.setRows(5);
        jScrollPane2.setViewportView(LGInfo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 170, 190));

        javax.swing.GroupLayout queuesPanelBGLayout = new javax.swing.GroupLayout(queuesPanelBG);
        queuesPanelBG.setLayout(queuesPanelBGLayout);
        queuesPanelBGLayout.setHorizontalGroup(
            queuesPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        queuesPanelBGLayout.setVerticalGroup(
            queuesPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        jPanel1.add(queuesPanelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        javax.swing.GroupLayout queuesPanelLGLayout = new javax.swing.GroupLayout(queuesPanelLG);
        queuesPanelLG.setLayout(queuesPanelLGLayout);
        queuesPanelLGLayout.setHorizontalGroup(
            queuesPanelLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        queuesPanelLGLayout.setVerticalGroup(
            queuesPanelLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(queuesPanelLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 200));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assest/Background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IAState.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BGInfo;
    private javax.swing.JLabel BGPoints;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel IAState;
    private javax.swing.JTextArea LGInfo;
    private javax.swing.JLabel LGPoints;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel queuesPanelBG;
    private javax.swing.JPanel queuesPanelLG;
    // End of variables declaration//GEN-END:variables
}
