/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSlider;
import proyectoso2.Main;


/**
 *
 * @author paola
 */
public final class Form extends javax.swing.JFrame {

    private final AllQueues queuesLG;
    private final AllQueues queuesBG;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        this.queuesLG = new AllQueues();
        this.queuesBG = new AllQueues();
        createQueues(queuesPanelLG, queuesLG);
        createQueues(queuesPanelBG, queuesBG);
    }
    
    public void createQueues(JPanel panel, AllQueues pq){
        pq.setSize(290, 330);
        pq.setLocation(0, 0);
        panel.removeAll();
        panel.add(pq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
    
    public void putInfo(){
        info1.setText("Name:");
        info2.setText("ID:");
        info3.setText("Points:");
        info4.setText("Name:");
        info5.setText("ID:");
        info6.setText("Points:");
        flag.setIcon(null);
    }
    
    public void clearInfo(){
        info1.setText("");
        info2.setText("");
        info3.setText("");
        info4.setText("");
        info5.setText("");
        info6.setText("");
        flag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/flag.png")));
    }
    
    public void changeIcon(String pathLG, String pathBG){
       imageLG.setIcon(new javax.swing.ImageIcon(getClass().getResource(pathLG)));
       imageBG.setIcon(new javax.swing.ImageIcon(getClass().getResource(pathBG)));
//       imageLG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LG1.jpg")));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LGWins = new javax.swing.JLabel();
        BGWins = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        results = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TimeSlider = new javax.swing.JSlider();
        IAState = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        queuesPanelLG = new javax.swing.JPanel();
        queuesPanelBG = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        imageLG = new javax.swing.JLabel();
        imageBG = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        nameLG = new javax.swing.JLabel();
        qualityLG = new javax.swing.JLabel();
        idLG1 = new javax.swing.JLabel();
        flag = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        info6 = new javax.swing.JLabel();
        info4 = new javax.swing.JLabel();
        info5 = new javax.swing.JLabel();
        idBG1 = new javax.swing.JLabel();
        nameBG = new javax.swing.JLabel();
        qualityBG = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(899, 504));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LGWins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LGWins.setText("0");
        jPanel1.add(LGWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 70, -1));

        BGWins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BGWins.setText("0");
        jPanel1.add(BGWins, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bugatti");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));

        results.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(results, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        TimeSlider.setMaximum(30);
        TimeSlider.setMinimum(1);
        TimeSlider.setValue(10);
        TimeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TimeSliderStateChanged(evt);
            }
        });
        jPanel1.add(TimeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        IAState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IAState.setText("Working");
        jPanel1.add(IAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("The IA is ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel4.setText("10");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 30, -1));

        jLabel6.setText("30");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 20, -1));

        queuesPanelLG.setOpaque(false);
        queuesPanelLG.setPreferredSize(new java.awt.Dimension(290, 330));

        javax.swing.GroupLayout queuesPanelLGLayout = new javax.swing.GroupLayout(queuesPanelLG);
        queuesPanelLG.setLayout(queuesPanelLGLayout);
        queuesPanelLGLayout.setHorizontalGroup(
            queuesPanelLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        queuesPanelLGLayout.setVerticalGroup(
            queuesPanelLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(queuesPanelLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, 330));

        queuesPanelBG.setBackground(new java.awt.Color(255, 51, 51));
        queuesPanelBG.setOpaque(false);
        queuesPanelBG.setPreferredSize(new java.awt.Dimension(350, 380));

        javax.swing.GroupLayout queuesPanelBGLayout = new javax.swing.GroupLayout(queuesPanelBG);
        queuesPanelBG.setLayout(queuesPanelBGLayout);
        queuesPanelBGLayout.setHorizontalGroup(
            queuesPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        queuesPanelBGLayout.setVerticalGroup(
            queuesPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(queuesPanelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 290, 330));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Lamborghini");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel1.add(imageLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 210, 120));
        jPanel1.add(imageBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 210, 120));
        jPanel1.add(info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, -1));
        jPanel1.add(info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));
        jPanel1.add(info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));
        jPanel1.add(nameLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));
        jPanel1.add(qualityLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));
        jPanel1.add(idLG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));
        jPanel1.add(flag, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel8.setText("1");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 30, -1));
        jPanel1.add(info6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 70, 20));
        jPanel1.add(info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 70, 20));
        jPanel1.add(info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 70, 20));
        jPanel1.add(idBG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 80, 20));
        jPanel1.add(nameBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 80, 20));
        jPanel1.add(qualityBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rsz_3extras.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TimeSliderStateChanged
        // TODO add your handling code here:
        Main.runTime = TimeSlider.getValue()*1000;
//        IAState.setText(String.valueOf(TimeSlider.getValue()));
    }//GEN-LAST:event_TimeSliderStateChanged
    
     
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
                 
            }
        });
    }
    
    public AllQueues getQueuesLG(){
        return queuesLG;
    }
    
    public AllQueues getQueuesBG(){
        return queuesBG;
    }
   
    public JLabel getIAState() {
        return IAState;
    }

    public void setIAState(JLabel IAState) {
        this.IAState = IAState;
    }

    public JLabel getBGWins() {
        return BGWins;
    }

    public JLabel getLGWins() {
        return LGWins;
    }

    public JLabel getResults() {
        return results;
    }

    public JLabel getIdLG1() {
        return idLG1;
    }

    public JLabel getNameLG() {
        return nameLG;
    }

    public JLabel getQualityLG() {
        return qualityLG;
    }

    public JLabel getImageLG() {
        return imageLG;
    }

    public JSlider getTimeSlider() {
        return TimeSlider;
    }

    public JLabel getIdBG1() {
        return idBG1;
    }

    public JLabel getImageBG() {
        return imageBG;
    }

    public JLabel getNameBG() {
        return nameBG;
    }

    public JLabel getQualityBG() {
        return qualityBG;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGWins;
    private javax.swing.JLabel IAState;
    private javax.swing.JLabel LGWins;
    private javax.swing.JSlider TimeSlider;
    private javax.swing.JLabel flag;
    private javax.swing.JLabel idBG1;
    private javax.swing.JLabel idLG1;
    private javax.swing.JLabel imageBG;
    private javax.swing.JLabel imageLG;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel info3;
    private javax.swing.JLabel info4;
    private javax.swing.JLabel info5;
    private javax.swing.JLabel info6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameBG;
    private javax.swing.JLabel nameLG;
    private javax.swing.JLabel qualityBG;
    private javax.swing.JLabel qualityLG;
    private javax.swing.JPanel queuesPanelBG;
    private javax.swing.JPanel queuesPanelLG;
    private javax.swing.JLabel results;
    // End of variables declaration//GEN-END:variables
}
