/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author paola
 */
public final class Form extends javax.swing.JFrame {

    private final AllQueues queuesLG;
    private final AllQueues queuesBG;
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.queuesLG = new AllQueues();
        this.queuesBG = new AllQueues();
        createQueues(queuesPanelLG, queuesLG);
        createQueues(queuesPanelBG, queuesBG);
        
    }
    
    public void createQueues(JPanel panel, AllQueues pq){
        pq.setSize(350, 380);
        pq.setLocation(0, 0);
        panel.removeAll();
        panel.add(pq, BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LGPoints = new javax.swing.JLabel();
        BGPoints = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TimeSlider = new javax.swing.JSlider();
        IAState = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        queuesPanelLG = new javax.swing.JPanel();
        queuesPanelBG = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(899, 504));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LGPoints.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LGPoints.setText("0");
        jPanel1.add(LGPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 70, -1));

        BGPoints.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BGPoints.setText("0");
        jPanel1.add(BGPoints, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bugatti");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Lamborghini");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        TimeSlider.setMaximum(30);
        TimeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TimeSliderStateChanged(evt);
            }
        });
        jPanel1.add(TimeSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        IAState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IAState.setText("Working");
        jPanel1.add(IAState, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("The IA is ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel4.setText("0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 30, -1));

        jLabel6.setText("30");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 20, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 380, 380));

        queuesPanelLG.setOpaque(false);
        queuesPanelLG.setPreferredSize(new java.awt.Dimension(350, 380));

        javax.swing.GroupLayout queuesPanelLGLayout = new javax.swing.GroupLayout(queuesPanelLG);
        queuesPanelLG.setLayout(queuesPanelLGLayout);
        queuesPanelLGLayout.setHorizontalGroup(
            queuesPanelLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        queuesPanelLGLayout.setVerticalGroup(
            queuesPanelLGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jPanel1.add(queuesPanelLG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 290, 330));

        queuesPanelBG.setOpaque(false);
        queuesPanelBG.setPreferredSize(new java.awt.Dimension(350, 380));

        javax.swing.GroupLayout queuesPanelBGLayout = new javax.swing.GroupLayout(queuesPanelBG);
        queuesPanelBG.setLayout(queuesPanelBGLayout);
        queuesPanelBGLayout.setHorizontalGroup(
            queuesPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        queuesPanelBGLayout.setVerticalGroup(
            queuesPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.add(queuesPanelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 290, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TimeSliderStateChanged
        // TODO add your handling code here:
        IAState.setText(String.valueOf(TimeSlider.getValue()));
    }//GEN-LAST:event_TimeSliderStateChanged
    
     
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    
    public AllQueues getQueuesLG(){
        return queuesLG;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGPoints;
    private javax.swing.JLabel IAState;
    private javax.swing.JLabel LGPoints;
    private javax.swing.JSlider TimeSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel queuesPanelBG;
    private javax.swing.JPanel queuesPanelLG;
    // End of variables declaration//GEN-END:variables
}
