/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JTextField;

/**
 *
 * @author paola
 */
public class Queue extends javax.swing.JPanel {

    /**
     * Creates new form Queue
     */
    public Queue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showQueue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(270, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showQueue.setEditable(false);
        showQueue.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        showQueue.setOpaque(false);
        showQueue.setPreferredSize(new java.awt.Dimension(270, 60));
        showQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQueueActionPerformed(evt);
            }
        });
        add(showQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 250, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void showQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQueueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showQueueActionPerformed

    public JTextField getShowQueue(){
        return showQueue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField showQueue;
    // End of variables declaration//GEN-END:variables
}
