/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JTextField;

/**
 *
 * @author paola
 */
public class Queue extends javax.swing.JPanel {

    /**
     * Creates new form Queue
     */
    public Queue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showQueue = new javax.swing.JTextField();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(270, 60));

        showQueue.setEditable(false);
        showQueue.setEnabled(false);
        showQueue.setPreferredSize(new java.awt.Dimension(270, 60));
        showQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQueueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQueueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showQueueActionPerformed

    public JTextField getShowQueue(){
        return showQueue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField showQueue;
    // End of variables declaration//GEN-END:variables
}
